### PR TITLE
feat/ XDC Chain and XDCSwap Connector

### PR DESCRIPTION
**Pull request by james-hummingbot**
**Before submitting this PR, please make sure**:

- [x] Your code builds clean without any errors or warnings
- [x] You are using approved title ("feat/", "fix/", "docs/", "refactor/")

**A description of the changes proposed in the pull request**:
Adds XDC Chain and XDCSwap and XSSwap connector into gateway.

Note: The large amount of changes is the result to having to include our own copy of `ethers-xdc` with changes made specifically for the XDC chain

[sc-36809]

**Tests performed by the developer**:
Added manual `curl` commands and included various unit tests

**Tips for QA testing**:
Ensure that both XDCSwap and XSSwap connector works as intended.
You will need to use this version of Hummingbot in PR [#312](https://github.com/CoinAlpha/hummingbot/pull/312) for it to work
You might need to use the `curl` commands to manual issue a token approval
Note: If testing on xinfin(mainnet) network, please verify that the WXDC address used is as follows:
xdc951857744785e80e2de051c32ee7b25f9c458c42

### CODE REVIEW

**Comment by mrhzysbl** [comment]
Test Run:
Gateway: https://hummingbot.testrail.io/index.php?/runs/view/3997&group_by=cases:section_id&group_order=asc 
XDCSwap: https://hummingbot.testrail.io/index.php?/runs/view/3999&group_by=cases:section_id&group_order=asc
XSSwap: https://hummingbot.testrail.io/index.php?/runs/view/4000&group_by=cases:section_id&group_order=asc

**Comment by rxlxrxsx** [comment]
- Getting this error immediately after starting the bot using the amm_arb strategy.

Screen Shot 2023-02-22 at 1 28 10 PM

- The same error is also seen when manually testing curl on buy/sell swap and getting xdc swap price.

Screen Shot 2023-02-22 at 1 45 25 PM

- Even though the tokens used are manually approved both on curl and the trading interface, the bot stuck waiting for allowances (This is on XDC Swap, pending test for XSwap).

Screen Shot 2023-02-22 at 1 55 45 PM

Logs and config: [gw_xdcswap_files.zip](https://github.com/CoinAlpha/gateway/files/10808265/gw_xdcswap_files.zip)

**Comment by rxlxrxsx** [comment]
@james-hummingbot I used this [version](https://github.com/CoinAlpha/hummingbot/pull/312).

**Comment by rxlxrxsx** [comment]
1. Updates after re-testing on the latest commit ([8f45340](https://github.com/CoinAlpha/gateway/pull/1/commits/8f45340baa02af10656635415415f2a57f4d764e)):

- No longer getting this error both on client and manual tests
> * Getting this error immediately after starting the bot using the amm_arb strategy.
> 
> Screen Shot 2023-02-22 at 1 28 10 PM
>
> * The same error is also seen when manually testing curl on buy/sell swap and getting xdc swap price.
> 
> Screen Shot 2023-02-22 at 1 45 25 PM


- This is still an issue on the latest commit
> * Even though the tokens used are manually approved both on curl and the trading interface, the bot stuck waiting for allowances (Only happens on XDC).
> 
> Screen Shot 2023-02-22 at 1 55 45 PM
> 
> Logs and config: [gw_xdcswap_files.zip](https://github.com/CoinAlpha/gateway/files/10808265/gw_xdcswap_files.zip)

2. Other observations seen on the latest commit:

- Running the curl commands for the allowance and approval returns the following error

Screen Shot 2023-02-23 at 12 04 49 PM

- Running the curl commands for the price and trade (buy and sell) returns the following error

Screen Shot 2023-02-23 at 12 04 24 PM

3. Testing is done on XSwap and confirmed no issues were found.

**Comment by aarmoa** [comment]
BizDev team confirmed we are not adding support for XDC. Closing the PR

**Pull request closed without merging**
